services:
  - type: web
    name: qx-auto-trade
    runtime: node
    plan: free
    buildCommand: npm install --prefix backend
    startCommand: node backend/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://testing:Testing%401234@cluster0.hpcm1wl.mongodb.net/90pips?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: qx_auto_trade_secret_key_2026
      - key: SMTP_HOST
        value: smtp.hostinger.com
      - key: SMTP_PORT
        value: '465'
      - key: SMTP_SECURE
        value: 'true'
      - key: SMTP_USER
        value: noreply@quotexautotrade.com
      - key: SMTP_PASS
        value: Noreplyqx@2026
      - key: SMTP_FROM_NAME
        value: QX AUTO TRADE
      - key: SMTP_FROM_EMAIL
        value: noreply@quotexautotrade.com
